///<reference path="./typings/bluebird/bluebird.d.ts"/>
import Promise = require("bluebird");

export enum TicketCodes {ABRD,AESL,AFKS,AFLT,AGRO,AKRN,ALBK,ALNU,ALRS,AMEZ,APTK,ARMD,ARSA,ASSB,AVAN,AVAZ,AVAZP,BANE,BANEP,BISV,BISVP,BLNG,BRZL,BSPB,CHEP,CHGZ,CHKZ,CHMF,CHMK,CHZN,CLSB,CLSBP,CNTL,CNTLP,DALM,DASB,DGBZ,DGBZP,DIOD,DIXY,DVEC,DZRD,DZRDP,ELTZ,ENRU,EONR,ERCO,FEES,FESH,FORTP,GAZA,GAZAP,GAZC,GAZP,GAZS,GAZT,GCHE,GMKN,GRAZ,GTLC,GTPR,GUMM,HALS,HIMC,HIMCP,HYDR,IDVP,IGST,IGST03,IGSTP,IRAO,IRGZ,IRKT,ISKJ,JNOS,JNOSP,KAZT,KAZTP,KBSB,KBTK,KCHE,KCHEP,KGKC,KGKCP,KLSB,KMAZ,KMEZ,KMTZ,KOGK,KRKN,KRKNP,KRKO,KRKOP,KROT,KROTP,KRSB,KRSBP,KRSG,KSGR,KTSB,KTSBP,KUBE,KUNF,KUSTP,KUZB,KZBE,KZMS,KZOS,KZOSP,LIFE,LKOH,LNTA,LNZL,LNZLP,LPSB,LSNG,LSNGP,LSRG,LVHK,MAGE,MAGEP,MAGN,MASZ,MERF,MFGS,MFGSP,MFON,MGNT,MGNZ,MGTS,MGTSP,MISB,MISBP,MMBM,MNFD,MOBB,MOEX,MORI,MOTZ,MRKC,MRKK,MRKP,MRKS,MRKU,MRKV,MRKY,MRKZ,MRSB,MSNG,MSRS,MSSB,MSST,MSTT,MTLR,MTLRP,MTSS,MUGS,MUGSP,MVID,NAUK,NBTR,NFAZ,NKNC,NKNCP,NKSH,NLMK,NMTP,NNSB,NNSBP,NPOF,NSVZ,NVNG,NVNGP,NVTK,ODVA,OFCB,OGKB,OMSH,OMZZP,OPIN,OSMP,OTCP,PAZA,PETR,PGIL,PHOR,PHST,PIKK,PLSM,PLZL,PMSB,PMSBP,POLY,PRFN,PRIM,PRMB,PRTK,PSBR,QIWI,RASP,RBCM,RDRB,REBR,RGSS,RKKE,RLMN,RLMNP,RNAV,RODNP,ROLO,ROSB,ROSN,ROST,RSEA,RSTI,RSTIP,RTGZ,RTKM,RTKMP,RTSB,RTSBP,RUALR,RUGR,RUSI,RUSP,RZSB,SAGO,SAGOP,SARE,SAREP,SBER,SBERP,SELG,SELGP,SELL,SEMZ,SIBN,SKYC,SNGS,SNGSP,STSB,STSBP,SVAV,SXPNP,SYNG,SZPR,TAER,TANL,TANLP,TASB,TASBP,TATN,TATNP,TAVR,TFKF,TGKA,TGKB,TGKBP,TGKD,TGKDP,TGKN,TGKO,TORS,TORSP,TRCN,TRMK,TRNFP,TRUDP,TTLK,TUCH,TUZA,UAZA,UCSS,UKUZ,UNAC,UNKL,URFD,URKA,URKZ,USBN,UTAR,UTII,VDSB,VGSB,VGSBP,VJGZ,VJGZP,VLHZ,VRAO,VRAOP,VRPH,VRSB,VRSBP,VSMO,VSYD,VSYDP,VTBR,VTGK,VTRS,VZRZ,VZRZP,WTCM,WTCMP,YAKG,YASH,YKEN,YKENP,YNDX,YRSB,YRSBP,YRSL,ZHIV,ZILL,ZMZN,ZMZNP,ZVEZ}

export enum ActionTypes {
    Buy = 1,
    BuyOnMargin,
    Sell,
    SellShort
}

export enum OrderTypes {
    Market = 1,
    Limit,
    Stop,
    StopLimit
}

export enum CurrencyCodes {
    USD,
    EUR,
    RUR
}

export enum ExpirationTypes {
    Day = 1, //current market session
    DayExt, //Day / Night or Night / Day
    GTC //Till cancel
}

export interface IPutOrderData {
    ticket: TicketCodes
    action: ActionTypes
    orderType: OrderTypes
    currency: CurrencyCodes
    quantity: number
    limitPrice?: number
    stopPrice?: number
    allOrNothing?: boolean
    expiration?: ExpirationTypes
    groupPortfolio?: number
    userOrderId?: number
}


export interface ITrader {
    connect(authParams:any): Promise<any>
    putOrder(data:IPutOrderData): Promise<any>
}

export interface ISecurity {
    ticket: TicketCodes
    code: string
    lotSize: number
}


